version: '3'
services: 
    server: 
        container_name: "eldiario_server"
        build: ./server
        ports: 
            - "8080:8080"
        depends_on: 
            - mongo

    mongo:
        image: mongo:4.2
        # container name is important for connection string
        container_name: "eldiario_mongo"
        ports: 
            - "27017:27017"
        
        # environment:
        #     MONGO_INITDB_ROOT_USERNAME: "$USERNAME"
        #     MONGO_INITDB_ROOT_PASSWORD: "$PWD"
        #     MONGO_INITDB_DATABASE: "$DBNAME"
